### ISSUE TITLE
Insights on the product tables

### ISSUE THREAD

**Issue by abhisheklokare** [ramortegui/e-commerce-db#2]
I was just going through the  DDL's provided. Could you give a little insights about the following tables:

1. products
2. product_statuses
3. product_categories
4. product_tags

What is the purpose of these tables? If possible could you give an example??

**Comment by ramortegui** [comment]
Hi @abhisheklokare,

Products (t-shirt). The product with their SKU, description, etc.
Product_statuses (discontinued, production, clearance).  Status of the product.
product_categories (clothes).  Hierarchy
product_tags (outdoor, indoor, runner, sport, summer, golf). Terms associated with the product to help filter or search in your web store.

For sure you can accomplish all of it in one table, but for querying, organization, and normalization, this could be a good approach.

Hope this helps.

Ruben.

**Comment by abhisheklokare** [comment]
Thanks for the insights!!
